name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"  # Only runs on version tags like v1.2.3
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_SKIP: "cp36-* pp* *-musllinux*"  # Combined skip rules
          CIBW_BEFORE_BUILD: "pip install numpy && pip install ."
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload built wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/

  publish:
    name: Publish to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist

